<div class="footer">
    <div class="container">
        <div class="row">
            <div class="footerDetails">
                <div class="col-md-1"></div>
                <div class= "col-md-7">
                    <ul class="footer-links">
                        <li><h4><a href=""></a>Made By Matthew Fisher Client Server Side Assignment</h4></li>

                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="../../js/JavaScriptCSS.js"></script>
</body>
</html>
